
<Project Sdk="Microsoft.VisualStudio.Sdk.Build">
  <PropertyGroup>
    <TargetFrameworks>vs17_14;vs18_11</TargetFrameworks>
    <GeneratePkgDefFile>False</GeneratePkgDefFile>
    <ExtensionType>VSSDK+VisualStudio.Extensibility</ExtensionType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
