name: .NET

on:
  push:
    branches: [ "main", "phase-2-docs", "preview" ]
  pull_request:
    branches: [ "main", "phase-2-docs", "preview" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
#   - name: Setup dotnet
#     uses: actions/setup-dotnet@v3
#     with:
#       global-json-file: global.json
    - name: Restore dependencies
      run: msbuild /t:restore New_Extensibility_Model/Samples/Samples.sln
    - name: Build
      run: msbuild /t:build New_Extensibility_Model/Samples/Samples.sln
